var annotated =
[
    [ "ASPHSURFM", "structASPHSURFM.html", "structASPHSURFM" ],
    [ "ASPHSURFR", "structASPHSURFR.html", "structASPHSURFR" ],
    [ "CMD", "structCMD.html", "structCMD" ],
    [ "CMDARGTOKEN", "structCMDARGTOKEN.html", "structCMDARGTOKEN" ],
    [ "complex_double", "structcomplex__double.html", "structcomplex__double" ],
    [ "complex_float", "structcomplex__float.html", "structcomplex__float" ],
    [ "DATA", "structDATA.html", "structDATA" ],
    [ "DM_SIM", "structDM__SIM.html", "structDM__SIM" ],
    [ "FOCMASK", "structFOCMASK.html", "structFOCMASK" ],
    [ "IMAGE", "structIMAGE.html", "structIMAGE" ],
    [ "IMAGE_KEYWORD", "structIMAGE__KEYWORD.html", "structIMAGE__KEYWORD" ],
    [ "IMAGE_METADATA", "structIMAGE__METADATA.html", "structIMAGE__METADATA" ],
    [ "kdhyperrect", "structkdhyperrect.html", "structkdhyperrect" ],
    [ "kdnode", "structkdnode.html", "structkdnode" ],
    [ "kdres", "structkdres.html", "structkdres" ],
    [ "kdtree", "structkdtree.html", "structkdtree" ],
    [ "LOGSHIM_CONF", "structLOGSHIM__CONF.html", "structLOGSHIM__CONF" ],
    [ "MaterialIndex", "structMaterialIndex.html", "structMaterialIndex" ],
    [ "MODULE", "structMODULE.html", "structMODULE" ],
    [ "OPTPIAACMCDESIGN", "structOPTPIAACMCDESIGN.html", "structOPTPIAACMCDESIGN" ],
    [ "OPTSYST", "structOPTSYST.html", "structOPTSYST" ],
    [ "res_node", "structres__node.html", "structres__node" ],
    [ "savethreadmsg", "structsavethreadmsg.html", "structsavethreadmsg" ],
    [ "symrec", "structsymrec.html", "structsymrec" ],
    [ "VARIABLE", "structVARIABLE.html", "structVARIABLE" ],
    [ "yy_buffer_state", "structyy__buffer__state.html", "structyy__buffer__state" ],
    [ "yy_trans_info", "structyy__trans__info.html", "structyy__trans__info" ],
    [ "yyalloc", "unionyyalloc.html", "unionyyalloc" ],
    [ "YYSTYPE", "unionYYSTYPE.html", "unionYYSTYPE" ],
    [ "ZERNIKE", "structZERNIKE.html", "structZERNIKE" ]
];