#!/bin/bash


# PIAACMC design example script / step by step operations
# run the commands in this script in the local working directory
# This script is meant to be run/read line by line to guide the user




# ===========================================
#    MAKE LOCAL COPY (SYM LINK) OF SCRIPTS
# ===========================================


# source code directory (change as needed)
srcdir="/home/olivier/src/Cfits/src/PIAACMCsimul/scripts"

ln -s $srcdir/syncscripts syncscripts
./syncscripts

# you should see the following scripts in the work directory:
# ./run
# ./runclean
# ./runopt
# ./runPIAACMC
# ./sim

# type "./run" (no arguments) to see current configuration parameters and write the parameters in ./conf directory
./run

# configuration parameters are listed as files: ./conf/conf_<PARAMETERNAME>.txt



# ===========================================
#    CREATE / IMPORT PUPIL
# ===========================================

# you may create / import your own pupil
# in this example, the pupil must be a 1024 x 1024 pixel FITS file, single precision floating point
# the pupil array size (1024 pix) must match the "size" parameter
# the pupil radius in this example is 200 pix, and must match beamrad/pscale
# the pupil central obstruction should match the coin parameter (0.3 in this example)
# if you wish to use your own pupil file, make sure you either match the array size and beam size (pix) of this example, or modify the size, beamrad, pscale and coin parameters according to your pupil file



# the name of the pupil file is "pup_1024.fits"




# examples directory (change as needed)


exampledir="/home/olivier/src/Cfits/src/PIAACMCsimul/examples"
cp $exampledir/pup_WFIRST1024.fits.gz pup_1024.fits.gz
gunzip pup_1024.fits.gz



# ===========================================
#    SET PARAMETER VALUES FOR PIAACMC
# ===========================================

# PIAA optics (PIAACMC)
echo "1" > ./conf/conf_PIAAmode.txt

# set pre-apodizer to pupil plane conjugation
echo "0.0" > ./conf/conf_prePIAA0maskpos.txt


# PIAA OPTICS DESIGN
echo "0.3" > conf/conf_coin.txt
echo "0.29" > conf/conf_coout.txt
echo "1.1" > conf/conf_fpmradld.txt

# LYOT STOP(S) DESIGN
echo "565" > conf/conf_lambda.txt
echo "1" > conf/conf_NBls.txt

# FOCAL PLANE MASK DESIGN
echo "Mirror" > conf/conf_fpmmaterial.txt
echo "2" > conf/conf_FPMsectors.txt
echo "22" > conf/conf_NBrings.txt
echo "1.60" > conf/conf_maskradld.txt
echo "-2.0e-6" > conf/conf_fpmminsag.txt
echo "2.0e-6" > conf/conf_fpmmaxsag.txt

# OPTIMIZATION PARAMETERS
echo "565" > conf/conf_mlambda.txt
echo "10" > conf/conf_mlambdaB.txt
echo "50" > conf/conf_ssize.txt

# OPTICAL DESIGN
echo "1024" > conf/conf_size.txt
echo "0.022" > conf/conf_beamrad.txt
echo "0.00011" > conf/conf_pscale.txt
echo "80" > conf/conf_Fratio.txt
echo "-2.302606" > conf/conf_PIAAsep.txt
echo "1.199997" > conf/conf_PIAA0pos.txt
echo "0" > conf/conf_invPIAAmode.txt
echo "-1.102609" >  conf/conf_prePIAA0maskpos.txt
echo "1.199997" >  conf/conf_postPIAA0maskpos.txt
echo "-4.5" > conf/conf_LyotZmin.txt
echo "0.5" > conf/conf_LyotZmax.txt


# ===========================================
#    CREATE PIAACMC MONOCHROMATIC DESIGN
# ===========================================

# run step 0: CREATE APODIZATION PROFILE AND PIAA OPTICS SHAPES FOR CENTRALLY OBSCURED CIRCULAR PUPIL APPROXIMATION
./run optsingle 1

# this operation should take approximately 3 minutes

# The following files will be created:

# Cmodes_1024.fits : Cosine modes
# Fmodes_1024.fits : Fourier modes

# in ./piaacmcconf_i000 directory :
# WFamp0_xxx.fits and WFpha0_xxx.fits: amplitude and phase in specific planes
# conjugations.txt : list of planes and conjugation distance to reference
# apo2Drad.fits  : amplitude apodization (entirely allocated to PIAA optics)

# PIAA_Mshapes.txt : aspheric optics shapes (r0 z0 r1 z1), unit [m]



# repeat above step to compute on-axis PSF
./run optsingle 2
# this operation should take approximately 1mn



# Specify input pupil geometry
./run optsingle 3
# this operation is almost instantaneous


# complete step 003 : Compute on-axis PSF
./run optsingle 4
# this operation should take approximately 1mn


# complete step 004 : compute Lyot stops shapes and locations
./run optsingle 5
# this step takes approximately 2hr
# the Lyot stops are named "LyotStop0.fits, LyotStop1.fits ...


# complete step 005 : optimize focal plane mask transm
./run optsingle 6
# -> piaacmcconf_i000/result_fpmt.log

# complete step 006 : compute Lyot stops shapes and locations, 2nd pass, LStransm0 throughput)
./run optsingle 7

# complete step 007 : tune PIAA shapes and focal plane mask transm, 10 cosine modes, 5 Fourier modes
./run optsingle 8
# to monitor optimization, view linoptval.txt with tail -f command

# complete step 008 :  tune PIAA shapes and focal plane mask transm, 20 cosine modes, 20 Fourier modes
./run optsingle 9
# to monitor optimization, view linoptval.txt with tail -f command

# complete step 009 : Compute Lyot stops shapes and locations, 3nd pass, throughput = LStransm1
./run optsingle 10

# complete step 010: Tune Lyot stops conjugations
./run optsingle 11 
# to monitor progress: tail -f result_LMpos.log 

# complete step 011 :  tune PIAA shapes and focal plane mask transm, 20 cosine modes, 20 Fourier modes
./run optsingle 12

# complete step 012 : tune PIAA shapes and focal plane mask transm, 40, 100
./run optsingle 13

# complete step 013 : Compute Lyot stops shapes and locations, 4rth pass, $LStransm2 throughput
./run optsingle 14

# complete step 014 : Tune Lyot stops conjugations
./run optsingle 15

# complete step 015 
./run optsingle 16

# skip steps 16 and 17
touch ./piaacmcconf_i000/step016.txt
touch ./piaacmcconf_i000/step017.txt


# propagate monochromatic solution (optional)
./run propmono 0
# [1] Total light in scoring field = 28915, peak PSF = 1.84375e+10, SCOTINGTOTAL = 324  -> Average contrast = 4.84035e-09


# ===========================================
#    FOCAL PLANE MASK DESIGN
# ===========================================

# select focal plane mask type: SiO2, transmission mask
echo "Mirror" > conf/conf_fpmmaterial.txt

# hexagonal tiling
echo "2" > conf/conf_FPMsectors.txt




echo "3.0" > conf/conf_maskradld.txt    # outer radius = 3.0 l/D
echo "32" > conf/conf_NBrings.txt		# Number of rings
echo "-2.0e-6" > conf/conf_fpmminsag.txt
echo "2.0e-6" > conf/conf_fpmmaxsag.txt
echo "50" > conf/conf_ssize.txt
echo "1.0" > conf/conf_fpmregsag_coeff.txt


# START FOCAL PLANE MASK DESIGN
time ./run optsingle 200

# measured contrast performance is 2nd number in ContrastVal_....

#  rings    mask rad    source     regularization    value                         unresolved         0.001 l/D       0.01 l/D       0.03 l/D

# 32 rings  3.0 l/D   ssize=50      reg=0.01  ->    3.8724e-08, Average contrast = 5.61627e-08		3.66916e-08		9.15693e-08		5.39727e-07
# 32 rings  3.0 l/D   ssize=50      reg=0.1   ->    1.0065e-09, Average contrast = 6.29330e-09		3.55166e-09		6.80190e-08		5.93530e-07
# 32 rings  3.0 l/D   ssize=50      reg=1.0   ->    2.8193e-10, Average contrast = 4.94036e-09		2.67363e-09		6.00026e-08		5.27830e-07
# 32 rings  3.0 l/D   ssize=50      reg=10.0  ->    2.4695e-10, Average contrast = 4.65744e-09 					
# 32 rings  3.0 l/D   ssize=50      reg=100.0 ->    2.1154e-10, Average contrast = 4.35287e-09

# 32 rings  3.0 l/D   ssize=20      reg=0.01  ->	4.1832e-08, Average contrast = 7.04972e-08		4.40613e-08		7.05408e-08		2.88584e-07
# 32 rings  3.0 l/D   ssize=20      reg=0.1   ->	3.1043e-09, Average contrast = 2.32142e-08		1.26858e-08		2.77492e-08		1.53159e-07
# 32 rings  3.0 l/D   ssize=20      reg=1.0   ->	1.9625e-09, Average contrast = 2.65421e-08		1.42888e-08		3.27611e-08		1.85560e-07
# 32 rings  3.0 l/D   ssize=20      reg=10.0  ->	1.8084e-09, Average contrast = 2.72116e-08	
# 32 rings  3.0 l/D   ssize=20      reg=100.0 ->	1.6206e-09, Average contrast = 1.92244e-08

# adding 4nm RMS of astig (0.01 l/D at 400nm)
# 32 rings  3.0 l/D   ssize=50      reg=0.01  ->	1.6562e-07, Average contrast = 6.95957e-07 
# 32 rings  3.0 l/D   ssize=50      reg=0.1   ->    6.9933e-08, Average contrast = 3.97405e-07 
# 32 rings  3.0 l/D   ssize=50      reg=1.0   ->    6.3399e-08, Average contrast = 3.98679e-07		4.35282e-07		4.99133e-07		1.01478e-06

# Testing astig solution on astig-free configuration
# cp ../../PIAACMC1024_WFIRSTast/piaacmcconf_i000/fpm_zonea_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits .
# cp ../../PIAACMC1024_WFIRSTast/piaacmcconf_i000/fpm_zonez_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits .
# 32 rings  3.0 l/D   ssize=50      reg=1.0   ->                Average contrast = 3.98679e-07		2.20694e-07		3.16471e-07		1.08995e-06

# Testing astig-free solution on astig configuration
# 32 rings  3.0 l/D   ssize=50      reg=1.0   ->                                                  	2.18580e-06		2.22402e-06		2.53591e-06


# 64 rings  4.0 l/D   ssize=50      reg=10.0  ->    3.5759e-08, Average contrast = 5.48219e-07
# 64 rings  4.0 l/D   ssize=50      reg=100.0 ->    2.8548e-08

# 64 rings  4.0 l/D   ssize=20 
# 64 rings  4.0 l/D   ssize=20      reg=100.0 ->   



# this command will run for a few hrs if the number of focal plane mask zones is large
# the complex amplitude response of each mask zone is computed 
# Several sub-processes are launched, each computing a subset of the total number of zones
# you can follow the progress of each subprocess in the corresponding tmux sessions
# the tmux session names are PID followed by FPMt<index>n<NBindex>
#
# as each subprocess computes zone responses, they are stored in FITS files FPMresp..._thread<index>.fits.tmp
# you can open/view these files to follow progress - each zone appears as a line, and files should fill from the bottom to the top
#
# when all threads complete, the files are merged into a single FPMresp file
#

# the optsingle 200 command includes both the creation of the FPMresp file (which is skipped if the file already exists) and a search for the optimal solution
#
# Finding the optimal solution requires multiple searches, so you can re-launch the optsingle 200 command multiple time
# Results are written in a file names piaacmcconf_i000/mode13_....opt.txt
# the 5th number (in parentheses) shows the best solution 
#
# The focal plane mask solution is stored as:
# fpm_zonez_s2_l0565_sr10_nbr032_mr200_minsag-01999_maxsag002000_ssr50_ssm0_Mirror_wb10.best.fits
#
#
# to stop optimization loop:
# touch piaacmcconf_i000/stoploop13.txt
#




# to compute the on-axis PSF and complex amplitudes for the best solution, execute:
./run proppoly 0
# this will take about 3mn
# OUTPUT :
# [1] Total light in scoring field = 145297, peak PSF = 1.7878e+10, SCOTINGTOTAL = 2436  -> Average contrast = 3.33627e-09
# FILES IN ./piaacmcconf_i000/
# fpm_sagmap_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits
# psfi0_ptsrc_sm0_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits

# to compute the on-axis PSF and complex amplitudes for the best solution, execute:
./run eval0 18
# result files written in ./eval0/


# to compute PSF, point source and extended source
./run eval1 18
# takes 59mn
# more accurate pt source measurement of contrast in ContrastVal_s2 ... , 2nd number
# extended source (+ OPD err)
# ContrastVal_extsrc20_.. and ContrastVal_extsrc15_
# OUTPUT FILES:
# psfi0_extsrc15_sm0_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits
# ContrastVal_extsrc15_sm0_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.txt
# ContrastCurve_extsrc15_sm0_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.txt
# 
#


# to test a different focal plane solution
# save previous solution
# cp fpm_zonez_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits fpm_zonez_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits.save
# cp fpm_zonea_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits fpm_zonea_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits.save
# replace solution
# cp fpm_zonea_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr20_ssm0_Mirror_wb10.fits fpm_zonea_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits
# cp fpm_zonez_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr20_ssm0_Mirror_wb10.fits fpm_zonez_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits
# restore previous configuration
# cp fpm_zonez_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits.save fpm_zonez_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits
# cp fpm_zonea_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits.save fpm_zonea_s2_l0565_sr10_nbr032_mr300_minsag-02000_maxsag002000_fpmreg001000_ssr50_ssm0_Mirror_wb10.fits



# focal plane mask solution :
#
# tmp_fpmsag.fits
# tmp_fpmCA_pha.fits
# tmp_fpmCA_ampl.fits
#
# PSF:
# psfi0.fits
#



