#!/bin/bash

NBARGS=9


if [ "$#" -ne $NBARGS ]; then
	echo ""
	echo "Run PIAACMC design"
	echo "	Arg #1  (fpmr) : focal plane mask radius (idealized)        $1"
	echo "	Arg #2  (coin) : input central obstruction                  $2"
	echo "	Arg #3  (coout): output central obstruction                 $3"
	echo "	Arg #4  (r)    : resolved source code (0=unresolved)        $4"
	echo "                           00: pt source"
	echo "                           10: 0.1 l/D"
	echo "                           20: 0.01 l/D"
	echo "                           30: 0.001 l/D"
	echo "	Arg #5  (em)   : extended source mode                       $5"
	echo "                           0 :  3 points (r^4 null)"
	echo "                           1 :  6 points (r^6 null)"
	echo "	Arg #6  (sr)   : spectral range [%]                         $6"
	echo "	Arg #7  (l)    : central lambda [nm]                        $7"
	echo "	Arg #8         : Design step(s) code (single integer)       $8"
	echo "	Arg #9  (i)    : Design index (3 digits)                    $9"
	echo "" 
	echo ""
	echo "Design step(s) code specifies which operation(s) should be performed - see table below"
	echo "" 
	echo "" 
	echo "EXAMPLE: ./sim1024 1.10 0.30 0.25 1 10 0800 3 000"
	echo " "
	echo "NOTES :"
	echo " - Source code in : PIAACMCsimul.c"
	echo " - Working directory is of the form: piaacmcconf_1_fpmr1.20_coin0.30_coout0.25_r1_sr10_l0550_i000" 
	echo " - Lower level script is ./runPIAACMC" 
	echo ""
	echo "DESIGN STEP(S) CODES :"
	cat doc_designcodes.txt
	echo ""
	exit
fi


fpmrad=$1
coin=$2
coout=$3

rmode=$4

emode=$5

tmp=$6
sprange=$(echo $tmp | sed 's/^0*//')

tmp=$7
lambda=$(echo $tmp | sed 's/^0*//')

designstep=$8
index=$9

echo "rmode = $rmode"
echo "sprange = $6 -> $sprange"
echo "lambda = $7 -> $lambda"

dircode=$(printf "1_fpmr%3.2f_coin%3.2f_coout%3.2f_r%02d_em%d_sr%02d_l%04d_i%03d" "$fpmrad" "$coin" "$coout" "$rmode" "$emode" "$sprange" "$lambda" "$index")
dirname="piaacmcconf_$dircode"
echo "$dirname" > dirname.txt



#dirname=piaacmcconf0${maskradcode}
echo "Directory name: $dirname"

if [ 500 -eq $8 ]; then
echo "500: SAVE AS REFERENCE"
dircode1=$(printf "1_fpmr%3.2f_coin%3.2f_coout%3.2f" "$fpmrad" "$coin" "$coout")
dirname1="piaacmcconf_$dircode1"
echo "$dirname1" > dirname1.txt
if [ ! -d $dirname1 ]; then
echo "CREARING DIRECTORY $dirname1"
mkdir -p $dirname1
cp $dirname/pupa0_1024.fits $dirname1/
cp $dirname/piaa0Cmodes.fits $dirname1/
cp $dirname/piaa0Fmodes.fits $dirname1/
cp $dirname/piaa1Cmodes.fits $dirname1/
cp $dirname/piaa1Fmodes.fits $dirname1/
cp $dirname/piaacmcparams.conf $dirname1/
cp $dirname/LyotStop*.fits $dirname1/
cp $dirname/PIAA_Mshapes.txt $dirname1/
cp $dirname/piaam0z.fits $dirname1/
cp $dirname/piaam1z.fits $dirname1/
cp $dirname/APOmodesCos.fits $dirname1/
cp $dirname/apo2Drad.fits $dirname1/
cp $dirname/APLCapo.*.info $dirname1/
cp $dirname/step0*.txt $dirname1/
cp $dirname/piaacmcparams_idealmonomask.conf $dirname1/
fi
exit
fi


# if the directory does not exit, but a reference does exist, then copy reference
if [ 501 -eq $8 ]; then
echo "501: LOAD REFERENCE"
dircode1=$(printf "1_fpmr%3.2f_coin%3.2f_coout%3.2f" "$fpmrad" "$coin" "$coout")
dirname1="piaacmcconf_$dircode1"
echo "$dirname1" > dirname1.txt
if [ -d $dirname1 ]; then
if [ ! -d $dirname ]; then
echo "IMPORTING MONOCHROMATIC SOLUTION ... "
sleep 2
echo "CREARING DIRECTORY $dirname"
mkdir -p $dirname
cp $dirname1/pupa0_1024.fits $dirname/
cp $dirname1/piaa0Cmodes.fits $dirname/
cp $dirname1/piaa0Fmodes.fits $dirname/
cp $dirname1/piaa1Cmodes.fits $dirname/
cp $dirname1/piaa1Fmodes.fits $dirname/
cp $dirname1/piaacmcparams.conf $dirname/
cp $dirname1/LyotStop*.fits $dirname/
cp $dirname1/PIAA_Mshapes.txt $dirname/
cp $dirname1/piaam0z.fits $dirname/
cp $dirname1/piaam1z.fits $dirname/
cp $dirname1/APOmodesCos.fits $dirname/
cp $dirname1/apo2Drad.fits $dirname/
cp $dirname1/APLCapo.*.info $dirname/
cp $dirname1/step0*.txt $dirname/
cp $dirname1/piaacmcparams_idealmonomask.conf $dirname/
fi
fi
exit
fi


echo "EXECUTING: ./runPIAACMC $dirname 1024 0.00011 pupWA_1024.fits $fpmrad $coin $coout $rmode $emode $sprange $lambda $designstep"
./runPIAACMC $dirname 1024 0.00011 pupWA_1024.fits $fpmrad $coin $coout ${rmode} ${emode} ${sprange} $lambda $designstep

#cp -rf $dirname ${dirname}_step$designstep


