#!/bin/bash


size=1024

pupfile="pup_$size.fits"


errorstatus=0 # if 1, stop code, print error message and it in file "errorstatus.txt"



errorfile="errorstatus.txt"
checkerrorstatus ()
{
if [ -f ${errorfile} ]
then
echo ""
echo "****** [$(date)] FATAL ERROR: script $0 : $(cat ${errorfile})"
echo "****** exit script $0"
echo "****** Manually remove file $errorfile to unlock"
echo "****** bye !"
echo ""
exit
fi
}

printhelp ()
{
	echo ""
	echo "------------------------------------------------------------------------------"
	echo ""
	echo "         RUN PIAACMC DESIGN / EVALUATION"
	echo "         this script is called by script runopt"
	echo ""
	echo ""
	echo ""
	echo "Syntax:"
	echo " $0 <1:designstep> <2:coin> <3:coout> <4:fpmrad> <5:lambda> <6:PIAAmaterial> <7:LStransm> <8:NBlyotstop> <9:mlambda> <10:mlambdaB> <11:NBrings> <12:maskradld> <13:ssize> <14:extmode> <15:fpmmaterial> <16:index>" 
	echo "Example : "
	echo " $0 optsingle    0.30     0.29         1.10       650          Mirror         0.75            4           850          10            22           1.60          15           0          Mirror      001"
	echo ""
	echo " 1     designstep  : see documentation"
	echo
	echo "Arguments specific to PIAACMC design excluding focal plane mask :"
	echo " 2    coin         : input central obstruction"
	echo " 3    coout        : output central obstruction"
	echo " 4    fpmrad       : nominal PIAACMC focal plane mask radius"
	echo " 5    lambda       : design wavelength"
	echo " 6    PIAAmaterial : PIAA optics material"
	echo " 7    LStransm     : Lyot stops geometric transmission"
	echo " 8    NBlyotstop   : Number of Lyot stops"
	echo "Note: other settings are specified as conf_.txt files:"
	echo "            conf_size.txt            [default = 1024]  : array size                                $size pix"
	echo "            conf_MdesignStepMax.txt  [default = 13]    : max design step for monochromatic design  $MdesignStepMax" 
	echo ""
	echo ""
	echo "Arguments specific to PIAACMC focal plane mask :" 
	echo " 9    mlambda      : mask wavelength [nm]"
	echo " 10   mlambdaB     : mask bandwidth [%]"
	echo " 11   NBrings      : number of rings in the focal plane mask"
	echo " 12   maskradld    : physical mask radius [l/D]"
	echo " 13   ssize        : extended source radius [-10 log(rad)]. 00 if point source"
	echo " 14   extmode      : extended source mode (0: 3pts, 1: 6pts)"
	echo " 15   fpmmaterial  : material used for the focal plane mask"
	echo ""
	echo " 16   index"
	echo ""
	echo "------------------------------------------------------------------------------"
	echo ""
}

NBARGS=16

if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
	printhelp
if [ "$#" -ne $NBARGS ]; then
	echo "$0: Illegal number of parameters ($NBARGS params required, $# entered)"
	echo "$0: Illegal number of parameters ($NBARGS params required, $# entered)" > $errorfile
	checkerrorstatus
fi
	exit
fi


# CHECK IF PUPIL EXISTS
if [ ! -f $pupfile ]
then
echo "File $pupfile missing" > $errorfile
checkerrorstatus
fi




designstep=$1

# arguments related to PIAACMC optical design, expect focal plane mask
coin=$2   # input central obstruction (linear)
coout=$3  # output central obstruction (linear)
fpmrad=$4   # nominal PIAA focal plane mask radius
tmp=$5
lambda=$(echo $tmp | sed 's/^0*//')
PIAAmaterial="$6"
LStransm=$7
NBlyotstop=$8

# arguments related to focal plane mask design
tmp=$9
mlambda=$(echo $tmp | sed 's/^0*//')

tmp=${10}
mlambdaB=$(echo $tmp | sed 's/^0*//')

NBrings=${11}
maskradld=${12}
ssize=${13}
extmode=${14}
fpmmaterial="${15}"

# configuration index
index=${16}





dircode=$(printf "1_coin%5.3f_coout%5.3f_fpmr%5.3f_l%04d_%s_lt%4.2f_ls%d_i%03d" "$coin" "$coout" "$fpmrad" "$lambda" "$PIAAmaterial" "$LStransm" "$NBlyotstop" "$index")
dirname="piaacmcconf_$dircode"
echo "$dirname" > dirname.txt




#dirname=piaacmcconf0${maskradcode}
echo "Directory name: $dirname"

if [ 500 -eq $9 ]; then
echo "500: SAVE AS REFERENCE"
dircode1=$(printf "1_coin%5.3f_coout%5.3f_fpmr%5.3f" "$coin" "$coout" "$fpmrad")
dirname1="piaacmcconf_$dircode1"
echo "$dirname1" > dirname1.txt
if [ ! -d $dirname1 ]; then
echo "CREARING DIRECTORY $dirname1"
mkdir -p $dirname1
cp $dirname/pupa0_1024.fits $dirname1/
cp $dirname/piaa0Cmodes.fits $dirname1/
cp $dirname/piaa0Fmodes.fits $dirname1/
cp $dirname/piaa1Cmodes.fits $dirname1/
cp $dirname/piaa1Fmodes.fits $dirname1/
cp $dirname/piaacmcparams.conf $dirname1/
cp $dirname/LyotStop*.fits $dirname1/
cp $dirname/PIAA_Mshapes.txt $dirname1/
cp $dirname/piaam0z.fits $dirname1/
cp $dirname/piaam1z.fits $dirname1/
cp $dirname/piaa0z.fits $dirname1/
cp $dirname/piaa1z.fits $dirname1/
cp $dirname/APOmodesCos.fits $dirname1/
cp $dirname/apo2Drad.fits $dirname1/
cp $dirname/APLCapo.*.info $dirname1/
cp $dirname/step0*.txt $dirname1/
cp $dirname/piaacmcparams_idealmonomask.conf $dirname1/
fi
exit
fi


# if the directory does not exit, but a reference does exist, then copy reference
if [ 501 -eq $9 ]; then
echo "501: LOAD REFERENCE"
dircode1=$(printf "1_coin%5.3f_coout%5.3f_fpmr%5.3f" "$coin" "$coout" "$fpmrad")
dirname1="piaacmcconf_$dircode1"
echo "$dirname1" > dirname1.txt
if [ -d $dirname1 ]; then
if [ ! -d $dirname ]; then
echo "IMPORTING MONOCHROMATIC SOLUTION ... "
sleep 2
echo "CREARING DIRECTORY $dirname"
mkdir -p $dirname
cp $dirname1/pupa0_1024.fits $dirname/
cp $dirname1/piaa0Cmodes.fits $dirname/
cp $dirname1/piaa0Fmodes.fits $dirname/
cp $dirname1/piaa1Cmodes.fits $dirname/
cp $dirname1/piaa1Fmodes.fits $dirname/
cp $dirname1/piaacmcparams.conf $dirname/
cp $dirname1/LyotStop*.fits $dirname/
cp $dirname1/PIAA_Mshapes.txt $dirname/
cp $dirname1/piaam0z.fits $dirname/ 
cp $dirname1/piaam1z.fits $dirname/
cp $dirname1/piaa0z.fits $dirname/ 
cp $dirname1/piaa1z.fits $dirname/
cp $dirname1/APOmodesCos.fits $dirname/
cp $dirname1/apo2Drad.fits $dirname/
cp $dirname1/APLCapo.*.info $dirname/
cp $dirname1/step0*.txt $dirname/
cp $dirname1/piaacmcparams_idealmonomask.conf $dirname/
fi
fi
exit
fi


echo "====== EXECUTING: ./runPIAACMC $dirname $size 0.00011 $pupfile $coin $coout $fpmrad $lambda $PIAAmaterial $LStransm $NBlyotstop $mlambda $mlambdaB $NBrings $maskradld $ssize $extmode $fpmmaterial $index $designstep"

# $fpmrad $coin $coout $rmode $emode $sprange $lambda $PIAAmaterial $designstep"
./runPIAACMC $dirname $size 0.00011 $pupfile $coin $coout $fpmrad $lambda $PIAAmaterial $LStransm $NBlyotstop $mlambda $mlambdaB $NBrings $maskradld $ssize $extmode $fpmmaterial $index $designstep
#$fpmrad $coin $coout ${rmode} ${emode} ${sprange} $lambda $PIAAmaterial $designstep

#cp -rf $dirname ${dirname}_step$designstep


