#!/bin/bash

# Designing PIAACMC


printhelp ()
{
echo "------------------------------------------------------------------------"
echo "                 PIAACMC DESIGN"
echo " Edit script to set PIAACMC design parameters"
echo " "
echo " Usage :"
echo " $0 <command>"
echo "  command : "
echo "     optsingle : optimize"
echo "     eval0 : level 0 evaluation"
echo "     eval1 : level 1 evaluation"
echo "     eval2 : level 2 evaluation"
echo "------------------------------------------------------------------------"
}

NBARGS=1

if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
	printhelp
if [ "$#" -ne $NBARGS ]; then
    echo "Illegal number of parameters ($NBARGS params required, $# entered)"
fi
	exit
fi

runoptcmd=$1




coin=0.315
coout=0.290

fpmradld=1.000
PIAAmaterial="CaF2"

LStransm=0.70
NBls=3
lambda=1600
mlambda=1630
mlambdaB=20
NBrings=16
maskradld=1.50
ssize=20
extmode=0 # 3 pts
fpmmaterial="Si"

fpmminsag="-1e-5"
fpmmaxsag="1e-5"
fpmccnbr=5
fpmccz=$fpmmaxsag
fpmocradld=50.0
fpmocz=$fpmmaxsag


# OPTIONAL ARGUMENTS

beamrad=0.009
pscale=0.000045
Fratio=26.0
r0lim=1.15
r1lim=1.50 
piaasep=0.096
piaa0pos=0.200

echo "$beamrad" > conf_PIAAbeamrad.txt
echo "$Fratio" > conf_Fratio.txt
echo "$r0lim" > conf_PIAAr0lim.txt
echo "$r1lim" > conf_PIAAr1lim.txt
echo "$piaasep" > conf_PIAAsep.txt
echo "$piaa0pos" > conf_PIAA0pos.txt


echo "18" > conf_MdesignStepMax.txt


./runopt $runoptcmd $pscale $coin $coout $fpmradld $lambda $PIAAmaterial $LStransm $NBls $mlambda $mlambdaB $NBrings $maskradld $ssize $extmode $fpmmaterial $fpmminsag $fpmmaxsag $fpmccnbr $fpmccz $fpmocradld $fpmocz 000

